package components;
/* THIS CLASS SIMULATES THE INSTRUCTION MEMORY (HOLDING THE PROGRAM)
* WHEN READING THE PROGRAM FILL THE CURRENT CLASS WITH STRINGS (INSTRUCTIONS)
* SIMULATE IT WITH DATASTRUCTURE (ARRAY 8albn)
*/
public class InstructionMemory {

}
